0.6.9 - 'FreeBSD' release

diff --git a/bin/tui-install b/bin/tui-install
--- a/bin/tui-install
+++ b/bin/tui-install
@@ -71,13 +71,13 @@ Where options are:
 		SF="release version"    # Search For
         
         	results=$(for a in $SF;do ls $e|$GREP $a;done)
-		resultsFiles=$(for each in $results;do [[ -f "$e/$each" ]] && printf "$each ";done)
+		resultsFiles=$(for each in $results;do [ -f "$e/$each" ] && printf "$each ";done)
         
 		for each in $resultsFiles
 		do      tmp=$(cat "$e/$each")
-			if [[ ! "cpe" = "${tmp:0:3}" ]]
+			if [ ! "cpe" = "${tmp:0:3}" ]
 			then    strcat=$(cat "$e/$each")
-			    	[[ ! "" = "$strcat" ]] && output="$strcat"
+			    	[ ! "" = "$strcat" ] && output="$strcat"
 			fi
 		done
 		printf "$(printf $strcat|$AWK {'printf $1'})"
@@ -86,11 +86,11 @@ Where options are:
 	# Returns arch, debian, redhat or unkown
 	#
     		out=""
-		if [[ -f /etc/redhat-release ]] 
+		if [ -f /etc/redhat-release ] 
 		then	out=redhat
-		elif [[ -f /etc/arch-release ]]
+		elif [ -f /etc/arch-release ]
 		then	out=arch
-		elif [[ -f /etc/debian_version ]]
+		elif [ -f /etc/debian_version ]
 		then	out=debian
 		else	out=unknown
 			# Do further checkings
@@ -109,7 +109,7 @@ Where options are:
 #
 #	Catching Arguments
 #
-	#[[ -z $1 ]] && printf "$help_text" && exit $RET_FAIL	## Uncomment to exit with help if nothing is passed
+	#[ -z $1 ] && printf "$help_text" && exit $RET_FAIL	## Uncomment to exit with help if nothing is passed
 	# A ':' after a char indicates that this option requires an argument
 	while getopts "bdhl:v" opt
 	do 	case $opt in
@@ -138,7 +138,7 @@ Where options are:
 #
 #	Display & Action
 #
-	[[ 0 -ne $UID ]] && \
+	[ 0 -ne $UID ] && \
 		tui-echo "$ME requires root access!" "$FAIL" && \
 		exit 1
 
@@ -192,12 +192,12 @@ Where options are:
 			tui-status $RET "Installed package: $app" && \
 				( $doLog && tui-log "$LOG" "Successfully installed: $app" ) || \
 				( $doLog && tui-log "$LOG" "Failed to install: $app" )
-			[[ 0 -eq $RET ]] && \
+			[ 0 -eq $RET ] && \
 				good_ones+=" $app" && ((count_good++)) || \
 				bad_ones+=" $app"
 			((count_total++))
 		done
-		[[ -z "$bad_ones" ]] && \
+		[ -z "$bad_ones" ] && \
 			tui-echo "There were $[ $count_total - $count_good ] errors, namely these:" "$bad_ones"
 	else	# Do all in one bunch
 		tui-echo "Installing $@"
@@ -205,7 +205,7 @@ Where options are:
 		$doLog && tui-log "$LOG" "Trying to execute: $cmd_all"
 		
 		$cmd_all > /dev/zero 1>/dev/zero 2>/dev/zero && RET=0 || RET=1
-		[[ -z "$RET" ]] && RET=1
+		[ -z "$RET" ] && RET=1
 		tui-status $RET "Installed: '${pkgs[@]}' " && \
 			 ( $doLog && tui-log "$LOG" "Successfully installed: '$pkgs'" ) || \
 			 ( $doLog && tui-log "$LOG" "Failed to install: '$pkgs'" )
diff --git a/bin/tui-list b/bin/tui-list
--- a/bin/tui-list
+++ b/bin/tui-list
@@ -56,7 +56,7 @@ Where options are:
 "
 #	-r(oman)		Use roman letters as numbers
 
-	#[[ -z $1 ]] && printf "$help_text" && exit $RET_FAIL	## Uncomment to exit with help if nothing is passed
+	#[ -z $1 ] && printf "$help_text" && exit $RET_FAIL	## Uncomment to exit with help if nothing is passed
 	# A ':' after a char indicates that this option requires an argument
 	SEP=") "
 	while getopts "ahnr" opt
@@ -85,7 +85,7 @@ Where options are:
 	# Or: aa-az ba-bz, etc
 		num=$1
 		out=""
-		[[ $num -gt 700 ]] && \
+		[ $num -gt 700 ] && \
 			list=( $(echo {a..z} {a..z}{a..z} {a..z}{a..z}{a..z} ))	|| \
 			list=( $(echo {a..z} {a..z}{a..z} )) 	# Be fast for letters in range..
 		out="${list[$num]}"
@@ -109,7 +109,7 @@ Where options are:
 			out=""
 			case $N in
 			0)	out+=""	;;
-			[123])	while [[ $N -gt 0 ]]
+			[123])	while [ $N -gt 0 ]
 				do	out+="$one"
 					N=$(($N-1))
 				done
@@ -118,12 +118,12 @@ Where options are:
 			5)	out+="$five"	;;
 			[678])	out+="$five"
 				N=$(($N-5))
-				while [[ $N -gt 0 ]]
+				while [ $N -gt 0 ]
 				do	out+="$one"
 					N=$(($N-1))
 				done
 				;;
-			9)	while [[ $N -lt 10 ]]
+			9)	while [ $N -lt 10 ]
 				do	out+="$one"
 					N=$(($N+1))
 				done
@@ -132,7 +132,7 @@ Where options are:
 			esac
 			echo "$out"
 		}
-		while [[ $len -gt 0  ]]
+		while [ $len -gt 0  ]
 		do	# There are letters to add
 			num=${input:0:1}
 			# Do action according position
@@ -147,7 +147,7 @@ Where options are:
 				Tfive=I\)
 				Tten=CCI\)\)
 				DEPTH=$[ $len - 3 ]	# 1 = 1000 = initial template
-				while [[ $DEPTH -gt 1 ]]
+				while [ $DEPTH -gt 1 ]
 				do	Tone="C$Tone)"
 					Tfive="C$Tfive)"
 					Tten="C$Tten)"
@@ -180,24 +180,24 @@ Where options are:
 		esac
 		
 		# Add the string to array, or print array
-		if [[ $CUR -le $MAX ]]
+		if [ $CUR -le $MAX ]
 		then	len=0
 			for O in "${OUT[@]}";do len=$[ $len + ${#O} ];done
 			sum=$[ $len + 2  + ( ${#BORDER_LEFT} * 2 ) ]
 			
-			if [[ $sum -lt $COLUMNS ]]
+			if [ $sum -lt $COLUMNS ]
 			then	OUT[$CUR]="${count}${SEP/  / }$OPT"
 				shown=false
 				CUR=$(( $CUR + 1 ))
 			else	tui-echo "${OUT[@]}" >> /dev/stderr
 				CUR=0 && unset OUT[@] 
-				[[ -z "$OPT" ]] && shown=true
+				[ -z "$OPT" ] && shown=true
 				OUT[$CUR]="${count}${SEP}$OPT"
 				CUR=$(( $CUR + 1 ))
 			fi
 		else 	tui-echo "${OUT[@]}" >> /dev/stderr
 			CUR=0 && unset OUT[@] 
-			[[ -z "$OPT" ]] && shown=true
+			[ -z "$OPT" ] && shown=true
 			OUT[$CUR]="${count}${SEP}$OPT"
 			CUR=$(( $CUR + 1 ))
 		fi
diff --git a/bin/tui-log b/bin/tui-log
--- a/bin/tui-log
+++ b/bin/tui-log
@@ -64,7 +64,7 @@ Where options are:
 #
 #	Catching arguments
 #
-	[[ -z $2 ]] && printf "$help_text" && exit $RET_FAIL
+	[ -z $2 ] && printf "$help_text" && exit $RET_FAIL
 	while getopts "hedtpus:v" opt
 	do 	case $opt in
 		h)	printf "$help_text"
@@ -81,15 +81,15 @@ Where options are:
 	shift $(($OPTIND - 1))
 	LOG="$1"
 	MSG="$2"
-	if [[ $leave_empty = false ]]
-	then 	[[ -z "$PRE" ]] && \
+	if [ $leave_empty = false ]
+	then 	[ -z "$PRE" ] && \
 			PRE="$(date +'%F %T') $SEP " || \
 			PRE="$PRE $SEP "
 	fi
 #
 #	Action
 #
-	if [[ ! -f "$LOG" ]]
+	if [ ! -f "$LOG" ]
 	then 	# Create log file, exit with message on error
 		# Prints basic log header
 		if ! touch "$LOG" 2>/dev/zero
@@ -104,7 +104,7 @@ Where options are:
 		printf "${PRE}${MSG}" | $GREP -q "$D" || \
 			( $GREP -q $D "$LOG" || tui-log -e "$LOG" "\n$daily_date_str" )
 	fi
-	while [[ " " = "${PRE:0:1}" ]] ;do PRE="${PRE:1}";done	# Remove leading spaces
+	while [ " " = "${PRE:0:1}" ] ;do PRE="${PRE:1}";done	# Remove leading spaces
 	$beVerbose && tui-echo "$MSG"
 	printf "${PRE}${MSG}\n" >> "$LOG"
 	
