0.7.6 release

diff --git a/bin/tui-conf-set b/bin/tui-conf-set
--- a/bin/tui-conf-set
+++ b/bin/tui-conf-set
@@ -49,6 +49,7 @@ Where options are:
 	-l		Lists values vailabel in the file
 	-c		Writes the VALUE, and stores VALUENAME in capital chars
 	-s		Writes the VALUE, and stores VALUENAME in lower chars
+	-v		Prints a status message wether or not the value could be saved
 "
 	OPT=""
 	VALUE=""
@@ -57,12 +58,14 @@ Where options are:
 	CAPS=false
 	SMALL=false
 	hadDollar=false
+	beVerbose=false
 	SD=","
+	Q="-q"	# Make grep quiet where required
 #
 #	Catching Arguments
 #
 	[ -z "$2" ] && printf "$help_text" && exit 1
-	while getopts "icslh" name
+	while getopts "icslhv" name
 	do 	case $name in
 		c)	CAPS=true
 			SMALL=false
@@ -78,16 +81,21 @@ Where options are:
 		h)	printf "$help_text"
 			exit $RET_HELP
 			;;
+		v)	beVerbose=true
+			;;
 		esac
 	done
 	shift $(($OPTIND - 1))
+	[ $# -lt 3 ] && \
+		tui-printf -S 1 "$ME: Requires 3 arguments: CONFFILE VARNAME VALUE" && \
+		exit 1
 	CONFFILE="$1"
 	VARNAME="$2"
 	VALUE="$3"
 	 
-	# Exit if it does not exist
+	# File does not exist yet
 	if [ ! -f "$CONFFILE" ]
-	then	 tui-bol-dir "$(dirname $CONFFILE)"
+	then	tui-bol-dir "$(dirname $CONFFILE)" || exit 1
                 touch "$CONFFILE"
 	fi
 #
@@ -97,16 +105,16 @@ Where options are:
 	SEARCH="$(echo $SEARCH|$SED -e 's/^[[:space:]]*//')"
 	
 	# Apply options
-	$SMALL && VARNAME="${VARNAME,,}"
-	$CAPS  && VARNAME="${VARNAME^^}"
+	$SMALL && VARNAME="${VARNAME,,}" && VALUE="${VALUE,,}"
+	$CAPS  && VARNAME="${VARNAME^^}" && VALUE="${VALUE^^}"
 	
 	# Check for quotes
-	printf  "$VALUE"|$GREP -q " " && \
+	printf  "$VALUE"|$GREP $Q '[\ $]' && \
 		REPLACE="$VARNAME=\"$VALUE\"" || \
 		REPLACE="$VARNAME=$VALUE"
 	
 	# Set proper SED 'divider'
-	if echo "$SEARCH$REPLACE"|$GREP -q "$SD"
+	if echo "$VALUE"|$GREP $Q "$SD"
 	then 	# Coma was found
 		SD="/"
 		printf "$REPLACE"|$GREP "$SD"|$GREP -q '\\' && SD="\\"	# backslash was found
@@ -115,31 +123,45 @@ Where options are:
 	fi
 	
 	# Troubles with VARIABLES due to chars that need to be escaped
-        if echo "$REPLACE" | $GREP '[%$+@\]'
+        if echo "$REPLACE" | $GREP $Q '[%$+@\]'
 	then	hadDollar=true
+		str_checker="$(echo $VALUE|$SED s,'\\\$','$',g)"
+	else	str_checker="$VALUE"
 	fi
 #
 #	Display & Action
 #
-	Q="-q"	# Make grep quiet
-	# Generate the command
-	# Use quotes if either one of the strings contains spaces
-	echo "$SEARCH$REPLACE" | $GREP $Q " " && \
-		cmd="$SED s${SD}\"${SEARCH}\"${SD}\"${REPLACE}\"${SD}g -i $CONFFILE" || \
-		cmd="$SED s${SD}${SEARCH}${SD}${REPLACE}${SD}g -i $CONFFILE"
-	
-	# Save changes
-	if ! $GREP $Q "${VARNAME}=" "$CONFFILE"
+	# Save changes, Append or change var=value?
+	if ! $GREP "${VARNAME}=" "$CONFFILE" | $GREP $Q -v ^"#"
 	then	# Its not there yet, just append it
-		$hadDollar && \
-			printf '%s\n' "$(eval $REPLACE)" >> "$CONFFILE" || \
-			printf "${REPLACE}\n" >> "$CONFFILE"
-	elif [ true = $hadDollar ]
-	then	# Remove the escape chars while saving it.
-		eval $cmd
-	else	#echo " CHECK THIS --- line :: $LINENO" > /dev/zero
-		$cmd
+		if $hadDollar
+		then	# It needs special treatement
+			echo "$(echo $REPLACE)" >> "$CONFFILE"
+		else	# Easy handling
+			echo "${REPLACE}" >> "$CONFFILE"
+			
+		fi
+	else	# Its already there, handling according to special chars
+		#set -x
+		
+		if $hadDollar
+		then	# It needs special treatement
+			SEARCH="$(echo $SEARCH|$SED s,'$','\$',g)"
+			cmd="$SED s${SD}\"${SEARCH}\"${SD}\"${REPLACE}\"${SD}g -i $CONFFILE"
+			eval "$cmd"
+		else	# It is simple to call
+			cmd="$SED s${SD}${SEARCH}${SD}${REPLACE}${SD}g -i $CONFFILE"
+			$cmd
+		fi
+		#set +x
 	fi
 	
 	# Return true if replaced string was found
-	$GREP -q "$REPLACE" "$CONFFILE"
+	if $GREP $Q "$str_checker" "$CONFFILE"
+	then	# Success, visual-report only if verbose is enabled
+		$beVerbose && tui-status 0 "Saved \"$CONFFILE\"" "$VARNAME=$str_checker"
+		exit 0
+	else	# It failed, visual-report only if verbose
+		$beVerbose && tui-status 1 "Could not write to \"$CONFFILE\""
+		exit 1
+	fi
