v0.9.3 - GNU RC 24

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,7 +22,7 @@
 #	Transformed:	2015.12.07
 #	Changed:	2015.12.13
 	script_name=configure
-	script_version=1.8.3
+	script_version=1.8.4
 #
 #	Description:
 #		This script automaticly generates,
@@ -61,16 +61,12 @@
 	unset DOWNLOAD_IF_MISSING DOWNLOAD GIT SVN
 	unset REQS DEPS DOCS MAKE PRIOR POST UNINSTALL CLEAN DISTCLEAN IGNORE CHECK INSTALLDIRS MOSTLYCLEAN MAINTAINER_CLEAN
 	unset doMakefile doGNU doTUI doRef
-	unset ${!DIR_*} #${![AZ]]*_DIR}
+	unset ${!DIR_*}
 #
-#	Set Commands, bypass alias'
+#	Set command-tools help output to english and bypass alias'
 #
 	export LC_ALL=C
-	AWK=\gawk
-	GREP=\grep
-	LS=\ls
-	SED=\sed
-	WHICH=\which
+	declare AWK=\gawk GREP=\grep LS=\ls SED=\sed WHICH=\which
 #
 #	Prepare cleared arrays and variables
 #
@@ -97,23 +93,28 @@
 	# List supported 'error message' languages here:
 	YASSI_LANGS=" "
 	# Parse for any found language, or fallback to 'en_GB'
-	for lng in $YASSI_LANGS en_GB;do [ "${LANG##\.*}" = "$lng" ] && break;done
-	case "${lng:-en_GB}" in
-	en_GB)	MSG_NO_CODE="Fatal error, could not retrieve project (${APP_NAME^^}) code!"
-		MSG_NO_CONFIG="Configuration file ($CFG) not found!"
-		MSG_NO_NAME="Missing APP_NAME..."
-		MSG_NO_INTERNET="No working internet connection found."
-		MSG_NO_REQS="Did not find the following required commands:"
-		MSG_CANNOT_EXE_DIR='Cannot execute a directory: $1!'
-		MSG_MISSING_CMDS="Please provide these commands before configuring $APP_NAME!"
-		MSG_NO_TEXI="The command 'texi2any' was not found, which is required to create this manual"
-		MSG_TARBALL_GOOD="Successfully created tarball"
-		MSG_TARBALL_BAD="There was an error building the tarball"
-		MSG_REQS_ONE="Please install at least one of these commands:"
-		MSG_REQS_OPTS="You might like to install one of these too:"
-		#MSG_=""
-		;;
-	esac
+	for lng in $YASSI_LANGS en_GB
+	do 	# If lng is not default, check if LANG and lng are the same lang, even if not country.
+		[ ! $lng = en_GB ] && L="${LANG##\.*}" && [ "${L/_*}" = "${lng/_*}" ] || continue
+		case "${lng:-en_GB}" in
+		en_*)	MSG_NO_CODE="Fatal error, could not retrieve project (${APP_NAME^^}) code!"
+			MSG_NO_CONFIG="Configuration file ($CFG) not found!"
+			MSG_NO_NAME="Missing APP_NAME..."
+			MSG_NO_INTERNET="No working internet connection found."
+			MSG_NO_REQS="Did not find the following required commands:"
+			MSG_CANNOT_EXE_DIR='Cannot execute a directory: $1!'
+			MSG_MISSING_CMDS="Please provide these commands before configuring $APP_NAME!"
+			MSG_NO_TEXI="The command 'texi2any' was not found, which is required to create this manual"
+			MSG_TARBALL_GOOD="Successfully created tarball"
+			MSG_TARBALL_BAD="There was an error building the tarball"
+			MSG_REQS_ONE="Please install at least one of these commands:"
+			MSG_REQS_OPTS="You might like to install one of these too:"
+			MSG_RERUN_CFG="Please rerun ./configure with your settings."
+			#MSG_=""
+			break
+			;;
+		esac
+	done
 #
 #	Default path list
 #
@@ -628,7 +629,7 @@
 			which wget 2>/dev/zero 1>/dev/zero && wget -O "${DOWNLOAD##*/}" "$DOWNLOAD"
 			[ ! -f "${DOWNLOAD##*/}" ] && return 1
 			tar -axf "${DOWNLOAD##*/}" ; cd tui-master
-		)
+		}
 		! get_it && echo "$MSG_NO_INTERNET" && exit 1
 		./configure --prefix=$PREFIX --chroot=$CHROOT
 		T=${PWD##*/}
@@ -764,7 +765,7 @@
 		fi
 	}
 	task_download() { #
-	#
+	# Downloads APP_NAME project according to provided options
 	#
 		doDL=false outdir=""
 		[ -z "$DOWNLOAD_IF_MISSING" ] && return # Nothing todo if its empty
@@ -806,14 +807,15 @@
 		cat >> "make-install" <<-EO_SCREEN
 		
 		create_dir="${FHS[${1,,}]}"
-		if [ ! -d "\$CHROOT\${create_dir%/*}" ]
-		then 	cd "\$CHROOT/usr/.."
+		if [ ! -d "\${CHROOT}\${create_dir%/*}" ]
+		then 	mkdir -p "\${CHROOT}/usr"
+			cd "\${CHROOT}/usr/.."
 		 	[ -d "\$CHROOT/usr\${create_dir%/*}" ] && [ -n "\${create_dir%/*}" ] && \\
-		 		ln -sf "usr\${create_dir%/*}" "./\${create_dir%/*}"
+		 		ln -sf "usr\${create_dir%/*}" "\${create_dir%/*}"
 		 	cd "\$OLDPWD"
 		fi
-		#[ -d "\$CHROOT\$create_dir" ] || \\
-			mkdir -p "\$CHROOT\$create_dir" || echo >/dev/zero
+		[ -d "\${CHROOT}/\$create_dir" ] || \\
+		 	mkdir -p "\${CHROOT}/\$create_dir" || echo >/dev/zero
 		EO_SCREEN
 	}
 	task_uninstall() { # INDEX CONTENT
@@ -828,10 +830,10 @@
 				if [ -d "${tr}" ]
 				then	for e in "./$tr/"*
 					do 	[ -d "$e" ] && \
-							echo "rm -fr ${DEST/$CHROOT}/${e##*/}" || \
-							echo "rm -f ${DEST/$CHROOT}/${e##*/}"
+							echo "rm -fr \${CHROOT}${DEST/$CHROOT}/${e##*/}" || \
+							echo "rm -f \${CHROOT}${DEST/$CHROOT}/${e##*/}"
 					done
-				else	echo "rm -f ${DEST/$CHROOT}/${tr##*/}"
+				else	echo "rm -f \${CHROOT}${DEST/$CHROOT}/${tr##*/}"
 				fi
 				;;
 			COMPLDIR)
@@ -839,10 +841,10 @@
 				if [ -d "$tr" ]
 				then	for this_compl in "$tr/"*
 					do 	tmp_compl="${this_compl/\$\{APP_NAME\}/$APP_NAME}"
-						echo "rm -f ${DEST/$CHROOT}/${tmp_compl##*/}"
+						echo "rm -f \${CHROOT}${DEST/$CHROOT}/${tmp_compl##*/}"
 					done
 				else	tr="${tr/\$\{APP_NAME\}/$APP_NAME}"
-					echo "rm -f ${DEST/$CHROOT}/${tr##*/}"
+					echo "rm -f \${CHROOT}${DEST/$CHROOT}/${tr##*/}"
 				fi
 				;;
 			APPDIR|ICONDIR|LOCALEDIR)
@@ -850,26 +852,28 @@
 					. ./$CFG
 					for F in $(cd ${!INDEX}/ ; find -type f )
 					do
-						[ ! -d "$F" ] && echo "rm -f ${DEST/$CHROOT}/${F##/*}"
+						[ ! -d "$F" ] && echo "rm -f \${CHROOT}${DEST/$CHROOT}/${F##/*}"
 					done
 				)
 				;;
 			*)	[ -d "$tr" ] && \
-					echo "rm -fr ${DEST/$CHROOT}/${tr##*/}" || \
-					echo "rm -f ${DEST/$CHROOT}/${tr##*/}"
+					echo "rm -fr \${CHROOT}${DEST/$CHROOT}/${tr##*/}" || \
+					echo "rm -f \${CHROOT}${DEST/$CHROOT}/${tr##*/}"
 				;;
 			esac
 		done
 		return 0
 	}
+	get_dir() { source "$REF" ; tmp="${1^^}";echo "${!tmp}";unset tmp;}
+	get_content() { source "$CFG" ; tmp="${1^^}";echo "${!tmp}";unset tmp;}
 	task_install() { # INDEX CONTENT
 	#
 	#
 		# Vars 
-		INDEX="$1" ; shift
+		INDEX="$1" ; shift ; ID=${INDEX^^}
 		DEST="${CHROOT}${FHS[${INDEX,,}]}"
 		# func
-		get_dir() { source "$REF" ; tmp="$1";echo "${!tmp}";unset tmp;}
+		# Get content is former get_dir
 		skip_this() { # Entry
 			A=$(get_dir DATADIR)
 			B=$(get_dir DOCDIR)
@@ -880,25 +884,28 @@
 			done
 			return 1
 		}
+		# Copy all CONTENT of INDEX, preserve same output dir!
+		tPath="$(get_dir ${INDEX})"
+		DEST="${DEST:-$tPath}"
+		#tFile="$(get_content ${INDEX})"
+		
 		# Parse each 'variable'
 		for item in "${@}"
-		do 	ID=${INDEX^^}
-			tPath="$(get_dir ${INDEX})"
-			tItem=$(eval echo $item)
-			DEST="${DEST:-$tPath}"
-			
-			# Something to do?
+		do 	# Something to do?
+			#tui-title "$item :: $@"
+			tItem="$(eval echo $item)"
 			[ -n "$tItem" ] && \
 				task_mkdir "$INDEX" >> make-install || \
 				continue
-			# Install this the simple way
+			# Get proper string/-formating
 			if [ "./" = "${item:0:2}" ] || [ -f "$item" ]
 			then	str="$item"
 			elif [ -d "$item" ]
 			then	str="$item/*"
-			else	str="${tItem}"
+			else	str="$tItem"
 			fi	
-			echo "cp -ar $str \"$DEST\"" >> "make-install"
+			# Install this the simple way
+			echo "cp -ar ${str} \"$DEST\"" >> "make-install"
 		done
 		# Copy it to chroot, but let end user remove it
 	}
@@ -1006,6 +1013,7 @@
 		touch make make-{install,uninstall,distclean}
 		$doGNU && touch make-clean make-dist
 		[ -n "$(echo ${DOCS[*]})" ] && touch make-install-all
+		[ -n "$(echo ${CHECK[*]})" ] && touch make-check
 		[ -n "$(echo ${CLEAN[*]})" ] && touch make-clean
 		[ -n "$(echo ${DISTCLEAN[*]})" ] && touch make-distclean
 		[ -n "$(echo ${INSTALLDIRS[*]})" ] && touch make-installdirs
@@ -1016,17 +1024,20 @@
 			[ -n "$(echo ${DOCS[$t]})" ] && touch make-doc-$t
 		done
 		# Write shebang and make the scripts executable
+		tmp_var="CHROOT=\${DESTDIR:-$CHROOT}"
 		for m in ./make*;do
 			printf '%s\n' "#!/usr/bin/env bash" > "$m" ; chmod +x $m
 			# Write special content
 			case "$m" in
 			make)		printf '%s\n' "source $REF" "$tmp_var" >> "$m"	;;
 			*install*)	tmp_var="CHROOT=\${DESTDIR:-$CHROOT}"
-					printf '%s\n' "source $REF" "$tmp_var" >> "$m"
+					printf '%s\n' "source $REF || { echo \"$MSG_RERUN_CFG\" ; exit 1; }" "$tmp_var" >> "$m"
 					if [ "$m" = "make-install" ] && ! echo "$CHROOT/$PREFIX"| $GREP -q -e /home -e /Users -e /users
 					then 	printf '%s\n' "[ \${UID:-0} -ne 0 ] && \\"  \
-						printf '\t%s\n' "echo \"To ${m/*-} '${APP_TITLE:-APP_NAME}', root access is required.\" && \\" "exit 99" >> "$m"
-					fi ; unset tmp_var 	;;
+						printf '\t%s\n' "echo \"To ${m/*-} '${APP_TITLE:-APP_NAME}', root access is required.\" && \\" "exit 1" >> "$m"
+					fi ; unset tmp_var
+					[ "./make-install" = "$m" ] &&   printf '%s\n' "[ -d \"\$CHROOT\" ] || mkdir -p \"\$CHROOT\"" >> "$m"
+					[ "./make-uninstall" = "$m" ] && printf '%s\n' "[ -d \"\$CHROOT\" ] || CHROOT=\"\""  >>  "$m"	;;
 			esac ; $VERBOSE && printf '%s\n' "set -x" >>  "$m"
 		done
 		# Write $REF handlers
@@ -1035,6 +1046,7 @@
 				"cp $REF ${CHROOT}${FHS[sysconfdir]}/$APP_NAME.conf" >> "make-install"
 			printf '%s\n' "rm -f ${CHROOT}${FHS[sysconfdir]}/$APP_NAME.conf" >> "make-uninstall"
 		fi
+		#[ -n "$CHROOT" ] && echo "mkdir -p $CHROOT{/bin,/etc,/share/$APP_NAME,/share/doc/$APP_NAME}" >> make-install
 	}
 	write_files_content() { #
 	# Write the actual content of the scripts
@@ -1067,7 +1079,7 @@
 				task_install "$index" "$tmp"
 				task_uninstall "$index" "$tmp" >> make-uninstall
 			done
-			[ -n "$CHROOT" ] && echo "cp -a $REF make-install \"${CHROOT}$DATADIR\"" >> "make-install"
+			[ -n "$CHROOT" ] && echo "cp -a $REF make-install \"\${CHROOT}\$DATADIR\"" >> "make-install"
 		}
 		# Actually write the content
 		for m in make*;do
@@ -1130,11 +1142,11 @@
 				./make)		printf '%s\n' "options:" "	./make"  >> "$M"				;;
 				./make-install-all)
 					 	if [ -f "$task" ];then
-					 		printf '%s\n' "./make" ./make-doc-* "DESTDIR=\$(DESTDIR) ./make-install" >> "$task"
+					 		printf '%s\n' "./make" ./make-doc-* "DESTDIR=\${DESTDIR} ./make-install" >> "$task"
 						fi 
-						[ -f "$task" ] && printf '%s\n' "${task/\.\/make-}:" "	DESTDIR=\$(DESTDIR) $task"  >> "$M"
+						[ -f "$task" ] && printf '%s\n' "${task/\.\/make-}:" "	DESTDIR=\${DESTDIR} $task"  >> "$M"
 						 ;;
-				./make-install)	[ -f "$task" ] && printf '%s\n' "${task/*-}:" "	DESTDIR=\$(DESTDIR) ${task}"  >> "$M" ;;
+				./make-install)	[ -f "$task" ] && printf '%s\n' "${task/*-}:" "	DESTDIR=\${DESTDIR} ${task}"  >> "$M" ;;
 				*-doc-*)	[ -f "$task" ] && printf '%s\n' "${task/*-}:" "	${task}"  >> "$M" 	;;
 				*)		[ -f "$task" ] && printf '%s\n' "${task/*-}:" "	${task}"  >> "$M" 		;;
 				esac
@@ -1222,7 +1234,7 @@
 #	Prepare Environment
 #
 	load_fhs
-	unset ${list_variables}
+	unset ${list_variables} ${!list_variables}
 	source "$CFG"
 	write_file_ref
 #
@@ -1230,7 +1242,7 @@
 #
 	task_download
 	write_file_headers
-	task_tui
+	$doTUI && task_tui
 	write_files_content
 	write_file_docs
 	write_file_make
