TUI 0.9.0d hotfix

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,13 +19,14 @@
 #
 #
 #	Created:	2015.07.27
-#	Changed:	2015.10.05
+#	Changed:	2015.11.02
 	script_name=configure
-	script_version=1.1.2
+	script_version=1.2
 #
 #	Description:
 #		This script automaticly, according to passed options, 
 #		generates the following files, named to go along with GNU Automake terminology.
+#		* make
 #		* make-install
 #		* make-uninstall
 #		* make-distclean
@@ -75,8 +76,9 @@
 	
 	# Bools
 	doRef=false		# Copy the REFERENCE file to SYSCONFDIR?
+	doMakefile=false	# Do not write a makefile by default
 	doTarball=false		# Create a redist tarball?
-	is_at_home=false	# Is it a system or user installation?
+	is_at_home=false	# Is it a system (false) or user (true) installation?
 #
 #	Internal Variables
 #
@@ -91,12 +93,13 @@
 	AWK=\awk		# Bypass aliases
 	GREP=\grep		# Bypass aliases
 	SED=\sed		# Bypass aliases
-	CONFIG="./$script_name.cfg"
+	# Accept shell preset, but get overwritten by option --config CONFIG
+	CONFIG="${CONFIG:-./$script_name.cfg}"
 	which sudo 1>/dev/zero 2>/dev/zero && \
 		install_prefix="sudo " || \
 		install_prefix="su -c "
 	mandirs="mandir $(echo man{1..9}dir)"
-	index_list="prefix bindir sbindir sysconfdir datarootdir datadir docdir htmldir infodir $mandirs compldir sharedstatedir localstatedir"
+	index_list="prefix bindir sbindir sysconfdir datarootdir datadir docdir htmldir infodir $mandirs dvidir pdfdir psdir compldir sharedstatedir localstatedir"
 	variable_list="";for i in $index_list;do variable_list+=" ${i^^}";done
 	TMP="$PWD/tmp.$$"
 	CHROOT=""
@@ -104,6 +107,28 @@
 #
 #	Functions
 #
+	write_makefile() { 
+	# Checks for existing scripts and adds them to the makefile
+	#
+		# Clear / Init makefile
+		local M="./Makefile"
+		echo "SHELL = /bin/sh" > "$M"
+		
+		for task in make install uninstall distclean
+		do 	case "$task" in
+			make)	[ -f "./make" ] && \
+					printf '%s\n' "PNONY: $task" \
+					"${task}:"  \
+					"	./make"  >> "$M" 
+				;;
+			*)	[ -f "./make-$task" ] && \
+					printf '%s\n' "PNONY: $task" \
+					"${task}:"  \
+					"	./make-${task}"  >> "$M" 
+				;;
+			esac
+		done
+	}
 	show_sample() {
 	# Prints a sample configure.cfg
 	# and exits
@@ -265,6 +290,7 @@ OPTIONS
 	--docdir DIR		project documentation root	(\$DATAROOTDIR/doc/${APP:-APPNAME})
 	--htmldir DIR		project documentation root	(\$DOCDIR)
 	--infodir DIR		info documentation		(\$DATAROOTDIR/info)
+	dvidir|pdfdir|psdir
 	
 	--compldir DIR		bash completion			(\$DATAROOTDIR/bash-completion/completions)
 	--localedir		locale-dependent data		(\$DATAROOTDIR/locale)
@@ -346,7 +372,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		# Prints the index reference used
 		#
 			ref_val="${FHS[${1,,}]}"
-			echo "${1}=$ref_val"  | sed s,"//","/",g
+			echo "${1}=$ref_val"  | \sed s,"//","/",g
 		}
 		write_uninstall() { # INDEX CONTENT
 		# Prints the remove commands
@@ -385,17 +411,53 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			done
 			return 0
 		}
+		write_remover() { # ENTRY
+		# Catches ENTRY and prints 'rm -f ENTRY' if it is a file/dir
+		# Print the line as-is otherwise
+			if [ -f "$1" ]
+			then 	echo "rm -f \"$1\""
+			elif [ -d "$1" ]
+			then 	echo "rm -fr \"$1\""
+			else	echo "$1"
+			fi
+		}
+		write_executer() { # ENTRY
+		# Catches ENTRY and prints 'sh ./ENTRY'
+		# Executes it, or fails if it is a dir.
+			if [ -d "$1" ]
+			then 	echo "DIR: $1, cannot execute!" >&2
+				exit 1
+			elif [ -f "$1" ]
+			then	[ "/" = "${1:0:1}" ] && \
+					echo "sh \"$1\"" || \
+					echo "sh \"./$1\""
+			else	echo "$1"
+			fi
+		}
 		write_distclean() { 
 		# Remove the files that where created
 		#
-			cat <<-EOF
+			echo "rm -f Makefile"
+			for task in make make-* $REFERENCE
+			do	write_remover "$task"
+			done
 			
-			rm -f "$REFERENCE"
-			rm -f ./make-* 
-			EOF
 		}
 		
 		# Prepare script headers
+		if [ -n "$(echo ${PREPARE[@]})" ] 
+		then	echo "#!/usr/bin/env sh" > "./make"
+			if ! $is_at_home 
+			then	echo "$CHROOT/$prefix"| grep -q -ve /home -ve /Users && \
+					printf '%s\n' \
+					"[ -z \$UID ] && UID=0" \
+					"[ \$UID -ne 0 ] && \\" \
+					"	echo \"To make preparations for '$APP', root access is required.\" && \\" \
+					"	exit 99" >> "./make"
+			fi
+			echo "set -x" >> "./make"
+			chmod +x "./make"
+		fi
 		for m in install uninstall distclean
 		do	echo "#!/usr/bin/env sh" > "make-$m"
 			if [ ! "$m" = "distclean" ] && ! $is_at_home 
@@ -409,6 +471,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			echo "set -x" >> "make-$m"
 			chmod +x "make-$m"
 		done
+		
 		$is_at_home && FHS[prefix]="$prefix_home"
 		echo "prefix=${FHS[prefix]}">"$REFERENCE"
 		if [ -n "$CHROOT" ] 
@@ -421,9 +484,8 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		then 	C=0
 			while 	item="${PREPARE[$C]}"
 				[ ! -z "$item" ]
-			do 	[ -f "$item" ] && \
-					bash ./"$item" || \
-					( echo "$item" > "$TMP" ; bash -x "$TMP" && rm -f "$TMP")
+			do 	write_executer "$item" >> "./make"
+				echo >> "./make"
 				((C++))
 			done
 		fi
@@ -435,9 +497,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			echo >> "make-install"
 			while 	item="${PRIOR[$C]}"
 			[ ! -z "$item" ]
-			do 	[ -f "$item" ] && \
-					echo "bash ./$item" >> "make-install" || \
-					echo "$item" >> "make-install" #  || exit 1
+			do 	write_executer "$item" >> "make-install"
 				((C++))
 			done
 		fi
@@ -512,9 +572,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			
 			while 	item="${CLEAN[$C]}"
 				[ -n "$item" ]
-			do 	( [ -f "./$item" ] || [ -f "$item" ] ) && \
-					echo "rm -f $item" >> "make-distclean" || \
-					echo "$item" >> "make-distclean"
+			do 	write_executer "$item" >> "make-distclean"
 				((C++))
 			done
 		fi
@@ -544,9 +602,11 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 				"RET=\$?" \
 				"set +x" >> "make-$m"
 		done
+		printf '%s\n' "RET=\$?" "set +x" >> "./make"
 		
 		# Let the script exit with their proper exit code.
 		echo "echo;echo \"Finished installation of ${APP_TITLE:-$APP} with \$? (0=success)\";exit \$RET" >> "make-install"
+		[ -f "./make" ] && echo "exit \$RET" >> "make"
 		echo "exit \$RET" >> "make-uninstall"
 		echo "exit \$RET" >> "make-distclean"
 		
@@ -558,7 +618,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 #
 	GETOPT=$(getopt \
 		--options	"h" \
-		--longoptions	"help,version,sample,sample-full,chroot:,tarball,bindir:,sbindir:,prefix:,datarootdir:,datadir:,infodir:,mandir,man[1-9]dir:,localedir:,docdir:,compldir:,sharedstatedir:,localstatedir:,localedir:" \
+		--longoptions	"help,version,config,write-makefile,sample,sample-full,chroot:,tarball,bindir:,sbindir:,prefix:,datarootdir:,datadir:,infodir:,mandir,man[1-9]dir:,localedir:,docdir:,compldir:,sharedstatedir:,localstatedir:,localedir:" \
 		--name 		"${0##*/}" -- "${@}"
 	)
 	eval set -- "$GETOPT"
@@ -569,14 +629,19 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 		--sample)	show_sample	;;
 		--sample-full)	show_sample_full;;
 		--prefix|--bindir|--sbindir|--datarootdir|--datadir|\
-		--infodir|--sysconfdir|--mandir,--man[1-9]dir|--docdir|--htmldir|\
+		--infodir|--sysconfdir|--mandir,--man[1-9]dir|--docdir|--htmldir|--dvidir|--pdfdir|--psdir|\
 		--compldir|--sharedstatedir|--localstatedir|--localedir)
 				FHS["${1/--}"]="$2"
 				shift 2		;;
 		--tarball)	doTarball=true
 				shift 		;;
+		--config)	CONFIG="$2"
+				shift 2		;;
 		--chroot)	CHROOT="$2"
 				shift 2		;;
+		--write-makefile)
+				doMakefile=true
+				shift		;;
 		--)		shift ; break	;;
 		esac
 	done
@@ -611,7 +676,7 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			man[0-9]dir)	tmp="${FHS[mandir]}/${index:0:4}" ;;
 			localedir)	tmp="${FHS[datarootdir]}/locale" ;;
 			docdir)		tmp="${FHS[datarootdir]}/doc/$APP" ;;
-			htmldir)	tmp="${FHS[docdir]}" ;;
+			htmldir|dvidir|pdfdir|psdir)	tmp="${FHS[docdir]}" ;;
 			compldir)	# Some systems have bash completion within the SYSCONFDIR
 					if [ -d "${FHS[datarootdir]}/bash-completion/completions" ]
 					then 	tmp="${FHS[datarootdir]}/bash-completion/completions"
@@ -715,7 +780,8 @@ Report bugs of $script_name to: https://github.com/sri-arjuna/yassi/issues
 			$opt_exclude * && \
 			echo "Successfully created tarball ${tarball}!"
 		set +x
-	else	[ -z "$CHROOT" ] &&  [ "$HOME" = "${prefix:0:${#HOME}}" ] && install_prefix=""
+	else	[ "$HOME" = "${prefix:0:${#HOME}}" ] && install_prefix=""
+		${doMakefile:-false} && write_makefile
 		echo
 		echo "The installation script has been configured to ${CHROOT}${FHS[prefix]} (${FHS[prefix]})."
 		echo "To install \"${APP_TITLE:-$APP}\" now, please execute: '${install_prefix}./make-install'"
diff --git a/templates/scripts/full b/templates/scripts/full
--- a/templates/scripts/full
+++ b/templates/scripts/full
@@ -47,7 +47,49 @@ cat > "$DEST" << EOF
 #
 #	TUI
 #
-	source tuirc
+	missing_tui() { 
+	# Checks if tui is installed, if not, downloads it either using git or curl/wget
+	# Returns true (0) if tuirc was found or was installed with success
+		# Lazy function
+		function is_there() { which "\$1" 2>/dev/zero 1>/dev/zero ; return \$? ;}
+		local tarball=tui.tar.gz
+		# Check for existence
+		if is_there tuirc
+		then 	return 0
+		else 	# Check for write access temp path
+			if [ -w /tmp ]
+			then 	cd /tmp
+			else	# Check for write access in home dir, existin paths
+				for D in cache temp tmp .temp .tmp .cache
+				do 	for H in "\$HOME" "\$HOME/.local" "\$HOME/local"
+					do 	[ -d "\$H/\$D" ] && cd "\$H/\$D" && break
+					done
+				done
+			fi
+			# Download TUI
+			if is_there git
+			then 	# Latest master contains latest bugfixes
+				git clone git://git.savannah.nongnu.org/tui.git
+				cd tui
+			elif is_there wget
+			then 	wget -O "\$tarball"
+			else 	curl -O "\$tarball"
+			fi
+			# Extract tarball if required
+			[ -f "\$tarball" ] && \\
+				tar -axf "\$tarball" && \\
+				rm -f "\$tarball" && \\
+				cd tui
+			# Dont require root acces
+			# Using default fallback mode for root user = /usr/local
+			# If its a regular user, dont be too visible
+			[ 0 -eq \${UID:-0} ] && \\
+				./configure || \\
+				./configure --prefix="\$HOME/.local"
+			./make-install && return 0
+		fi
+	}
+	missing_tui && source tuirc || { echo "Installation of TUI (Text User Interface, framework for scripts) failed!" ; exit 0 ; }
 	script_name="\${0##*/}"
 	script_name="\${script_name/.sh/}"
 	script_title="${DEST##*/}"
@@ -63,10 +105,11 @@ cat > "$DEST" << EOF
 	[ ! "." = "\$(dirname \$0)" ] && \\
 		script_dir="\$(dirname \$0)" || \\
 		script_dir="\$(pwd)"
+	# Shorts
 	CFG="\$script_config"
 	LOG="\$TUI_DIR_LOGS/\${script_name}.log"
 	TMP="\${TMPDIR}/\${script_name}-\$\$.tmp~"
-	REQUIRES="awk grep sed ls"
+	REQUIRES="awk ls grep sed"
 #
 #	Gettext
 #
@@ -95,7 +138,7 @@ This is free software; you are free to change and redistribute it.
 There is NO WARRANTY, to the extent permitted by law.
 ')"
 	MSG_TR_HELP="\$(eval_gettext 'SYNTAX
-	\$script_name [options] arguments ...')"
+	\$script_name [options] arguments ...
 
 OPTIONS
 	-h|--help		Shows this screen and exits
@@ -118,7 +161,7 @@ For more help on how to use GNU-Software: <http://www.gnu.org/gethelp/>
 #
 	first_use() {
 	# Write the initial configuration file
-	#
+	# Starting with a comment line indicating the author, script name and script version
 		tui-bol-dir "\$(dirname "\$script_config")"
 		cat > "\$script_config" <<-EOF
 		# \$MSG_TR_CONFIG_BY: \$script_name (\$script_version)
