tui-new-script, added and renamed a template

diff --git a/templates/scripts/application b/templates/scripts/application
--- a/templates/scripts/application
+++ b/templates/scripts/application
@@ -136,7 +136,7 @@ Tempfile:	\$TEMPFILE
 	# Checks if \$LOG exists
 	# If not, create default header
 		# This is optimized for a one-time setup
-		if [[ ! -e "\$LOG" ]] && $beLog
+		if \$beLog && [[ ! -e "\$LOG" ]]
 		then	[[ -d "\$CONFIG_DIR" ]] || mkdir -p "\$CONFIG_DIR"
 			if touch "\$LOG"
 			then	doLog "------------------------------------------" && \\
@@ -149,12 +149,12 @@ Tempfile:	\$TEMPFILE
 			fi
 		fi
 	}
-	if $beLog 
-	then	checkLog || exit $?
-	fi
 #
 #	Environment checks
 #
+	if \$beLog 
+	then	checkLog || exit \$?
+	fi
 	[[ ! -f "\$CONFIG" ]] && \\
 		echo "\$config_template" > "\$CONFIG"
 ## TODO : Remove this 'source block' if you want to read the variables from CONFIG manualy
@@ -177,10 +177,12 @@ Tempfile:	\$TEMPFILE
 			fi
 		done
 	fi
+	R=""
 #
 #	Catching Arguments
 #
 	# A ':' after a char indicates that this option requires an argument
+	# Get access to the passed value of the argument by using \$OPTARG
 	while getopts "ChLqv" opt
 	do 	case \$opt in
 		h)	printf "\$help_text"
@@ -227,4 +229,8 @@ Tempfile:	\$TEMPFILE
 	tui-echo "Logfile:" 		"\$LOG"
 	tui-echo "Configuration:" 	"\$CONFIG"
 	tui-echo "Temp file:"		"\$tempfile"
+#
+# 	Clean up & exit
+#
+	[[ -f "\$TEMPFILE" ]] && rm -fr "\$TEMPFILE"
 EOF
diff --git a/templates/scripts/default b/templates/scripts/default
--- a/templates/scripts/default
+++ b/templates/scripts/default
@@ -48,6 +48,10 @@ cat > "$DEST" << EOF
 	CONFIG="\$CONFIG_DIR/\$ME.conf"			# Configuration file
 	TEMPFILE="\$TUI_TEMP_DIR/\$ME.tmp"		# Tempfile
 #
+#	Variable defaults (options)
+#
+	beVerbose=false
+#
 #	Help text
 #
 #	TODO
@@ -62,6 +66,9 @@ Examples:	\$ME
 		\$ME -e optVAL
 Where options are:
 	-h(elp) 		This screen
+	-C(onf			Show the config menu
+	-q(uiet)		Mutes all output
+	-v(erbose)		Enables the scripts verbosity
 	
 
 Files:
@@ -73,33 +80,93 @@ Config_Dir:	\$CONFIG_DIR
 Tempfile:	\$TEMPFILE
 "
 #
+# This script requires TUI - Text User Interface
+# See:		https://github.com/sri-arjuna/tui
+#
+#	Check if TUI is installed...
+#
+	S=\$(which tui 2>/dev/zero )
+	if [[ ! -f \$S ]]
+	then 	[[ ! 0 -eq \$UID ]] && \\
+			printf "\\n#\\n#\\tPlease restart the script as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
+			exit 1
+		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
+		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
+			curl --progress-bar -L https://github.com/sri-arjuna/tui/archive/master.zip -o master.zip
+			unzip master.zip && rm -f master.zip
+			mv tui-master/* . ; rmdir tui-master
+		fi
+    		sh /tmp/tui.inst/install.sh || \\
+    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\n#\\n";exit 1)
+    	fi
+    	source \$S ; S=""
+#
+#	Configuration file template
+#
+#
+	config_template="# Configuration file for \$ME (\$script_version)
+#
+#	Booleans
+#
+	beVerbose=false
+	beQuiet=false
+#
+#	Variables
+#
+	DIR_CONFIG=\"\$HOME/.config/\$ME\"
+	TEMPFILE=\"\$DIR_CONFIG/tmp.tmp~)\"
+"
+#
 #	Functions
 #
 	
+#
+#	Environment checks
+#
+	[[ ! -f "\$CONFIG" ]] && \\
+		echo "\$config_template" > "\$CONFIG"
+## TODO : Remove this 'source block' if you want to read the variables from CONFIG manualy
+	# Load default values before parsing options
+	if ! source "\$CONFIG" 
+	then	# Could not source the configuuration...
+		tui-status 1 "Failed to load: \$CONFIG"
+	fi
 #
 #	Catching Arguments
 #
 	# A ':' after a char indicates that this option requires an argument
 	# Get access to the passed value of the argument by using \$OPTARG
-	while getopts "h" opt
+	while getopts "Chqv" opt
 	do 	case \$opt in
 		h)	printf "\$help_text"
 			exit \$RET_HELP
 			;;
-		*)	printf "\$help_text" 
-			exit \$?
+		C)	tui-conf-editor \\
+				-t \"\$TITLE - Configuration\" \\
+				-l \"\$LOG\" \\
+				\"\$CONFIG\"
+				
+			exit \$RET_DONE
 			;;
+		q)	beQuiet=true
+			log_msg="Forced silence"
+			;;
+		v)	beVerbose=true
+			log_msg="Enabled verbosity"
+			;;
+		*)	printf "\$help_text" ; exit \$?	;;
 		esac
+		\$beVerbose && \\
+			tui-echo "\$log_msg"
 	done
 	shift \$((\$OPTIND - 1))	# All options and they (if applicable) mandatory argument are removed
 	ARGS=("\${*}")			# Remaining arguments
 	ARGS_COUNT=\${#ARGS[@]}		# Amount of remaining
 #
-#	Action & Display
+#	Display & Action
 #
 	tui-header "\$ME (\$script_version)" "\$(date +'%F %T')"
 	tui-title "\$TITLE"
-
 	
 #
 # 	Clean up & exit
diff --git a/templates/scripts/tool b/templates/scripts/tool
--- a/templates/scripts/tool
+++ b/templates/scripts/tool
@@ -23,7 +23,7 @@ cat > "$DEST" << EOF
 #
 # ------------------------------------------------------------------------
 #
-	s=/bin/tui ; [[ -f \$s ]] && . \$s  && s=
+	s=/bin/tui ; [[ -f \$s ]] && . \$s  ; s=
 #
 #	File:		${DEST##*/}
 #	Author: 	$USER_NAME
@@ -45,12 +45,18 @@ cat > "$DEST" << EOF
 		ME_DIR="\$(dirname \$0)" || \\
 		ME_DIR="\$(pwd)"			# Dirname of ${DEST##*/}
 	CONFIG_DIR="\$HOME/.config/\$ME"		# Configuration directory
-	CONFIG="\$CONFIG_DIR/\$ME.conf"			# Configuration file
-	TEMPFILE="\$TUI_TEMP_DIR/\$ME.tmp"		# Tempfile
+	CONFIG="\$CONFIG_DIR/\$ME.conf"		# Configuration file
+## TODO
+## If you need more configuration files, simply add them, within quotes, to the array below
+	LOG="\$CONFIG_DIR/\$ME.log"		# Logfile
+	TEMPFILE="\$CONFIG_DIR/\$ME.tmp"		# Tempfile
+	REQUIRES="tui bash"
 #
 #	Variable defaults (options)
 #
 	beVerbose=false
+	beQuiet=false
+	beLog=true
 #
 #	Help text
 #
@@ -61,12 +67,13 @@ cat > "$DEST" << EOF
 \$ME (\$script_version)
 \${TITLE^}
 Usage: 		\$ME [options] arguments
-Examples:	\$ME 
-		\$ME -a
+Examples:	\$ME -v
+		\$ME -q
 		\$ME -e optVAL
 Where options are:
 	-h(elp) 		This screen
 	-C(onf			Show the config menu
+	-L(og)			Show the log file (\$LOG)
 	-q(uiet)		Mutes all output
 	-v(erbose)		Enables the scripts verbosity
 	
@@ -77,29 +84,9 @@ Script:		\$ME
 Script-Dir:	\$ME_DIR
 Config: 	\$CONFIG
 Config_Dir:	\$CONFIG_DIR
+Log:		\$LOG
 Tempfile:	\$TEMPFILE
 "
-#
-# This script requires TUI - Text User Interface
-# See:		https://github.com/sri-arjuna/tui
-#
-#	Check if TUI is installed...
-#
-	S=\$(which tui 2>/dev/zero )
-	if [[ ! -f \$S ]]
-	then 	[[ ! 0 -eq \$UID ]] && \\
-			printf "\\n#\\n#\\tPlease restart the script as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
-			exit 1
-		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
-		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
-			curl --progress-bar -L https://github.com/sri-arjuna/tui/archive/master.zip -o master.zip
-			unzip master.zip && rm -f master.zip
-			mv tui-master/* . ; rmdir tui-master
-		fi
-    		sh /tmp/tui.inst/install.sh || \\
-    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\n#\\n";exit 1)
-    	fi
-    	source \$S ; S=""
 #
 #	Configuration file template
 #
@@ -110,42 +97,88 @@ Tempfile:	\$TEMPFILE
 #
 	beVerbose=false
 	beQuiet=false
+	beLog=false
 #
 #	Variables
 #
 	DIR_CONFIG=\"\$HOME/.config/\$ME\"
-	TEMPFILE=\"\$DIR_CONFIG/tmp.tmp~)\"
+	TEMPFILE=\"\$DIR_CONFIG/tmp.\$\$~)\"
 "
 #
 #	Functions
 #
-	
+	doLog() { # "MESSAGE STRING"
+	# Prints: Time & "Message STRING"
+	# See 'tui-log -h' for more info
+		tui-log -t "\$LOG" "\$1"
+	}
+	checkLog() { #
+	# Checks if \$LOG exists
+	# If not, create default header
+		# This is optimized for a one-time setup
+		if \$beLog && [[ ! -e "\$LOG" ]]
+		then	[[ -d "\$CONFIG_DIR" ]] || mkdir -p "\$CONFIG_DIR"
+			if touch "\$LOG"
+			then	doLog "------------------------------------------" && \\
+				doLog "Created logfile of \$ME (\$script_version)" && \\
+				doLog "------------------------------------------" && \\
+				doLog "Setup : First config"
+				\$0 -C
+			else	tui-status 1 "Could not create \$LOG"
+				return \$?
+			fi
+		fi
+	}
 #
 #	Environment checks
 #
+	# Create initial log file if logging is enabled
+	if \$beLog 
+	then	checkLog || exit \$?
+	fi
+	
+	# Create configuration file from template if not exist yet
 	[[ ! -f "\$CONFIG" ]] && \\
-		echo "\$config_template" > "\$CONFIG"
+		( tui-bol-dir "\$CONFIG_DIR" && echo "\$config_template" > "\$CONFIG" )
+
 ## TODO : Remove this 'source block' if you want to read the variables from CONFIG manualy
 	# Load default values before parsing options
 	if ! source "\$CONFIG" 
 	then	# Could not source the configuuration...
+		\$beLog && doLog "Failed to load: \$CONFIG" 
 		tui-status 1 "Failed to load: \$CONFIG"
+	fi
+#
+#	Install missing packages
+#
+	R=\$(tui-conf-get \"\$CONFIG\" reqs_installed)
+	if [[ ! true = "\$R" ]]
+	then	for req in \$REQUIRES;do
+			tui-printf "Verifying: \$req..." "\$(tui-indi)"
+			if ! which \$req 2>/dev/zero 
+			then	\$beLog && doLog -v "Installing: $req"
+				tui-install \$req
+			fi
+		done
 	fi
 #
 #	Catching Arguments
 #
 	# A ':' after a char indicates that this option requires an argument
-	while getopts "Chqv" opt
+	# Get access to the passed value of the argument by using \$OPTARG
+	while getopts "ChLqv" opt
 	do 	case \$opt in
 		h)	printf "\$help_text"
 			exit \$RET_HELP
+			;;
+		L)	less "\$LOG"	
+			exit \$RET_DONE
 			;;
 		C)	tui-conf-editor \\
 				-t \"\$TITLE - Configuration\" \\
 				-l \"\$LOG\" \\
 				\"\$CONFIG\"
-				
-			exit \$RET_DONE
+			exit \$?
 			;;
 		q)	beQuiet=true
 			log_msg="Forced silence"
@@ -155,19 +188,35 @@ Tempfile:	\$TEMPFILE
 			;;
 		*)	printf "\$help_text" ; exit \$?	;;
 		esac
+		\$beLog && \\
+			doLog "Options: \$log_msg"
 		\$beVerbose && \\
 			tui-echo "\$log_msg"
 	done
 	shift \$((\$OPTIND - 1))	# All options and they (if applicable) mandatory argument are removed
 	ARGS=("\${*}")			# Remaining arguments
-	ARGS_COUNT=\${#ARGS[@]}		# Amount of remaining
+	ARGS_COUNT=\${#ARGS[@]}		# Amount of remaining arguments
 #
 #	Display & Action
 #
-	tui-header "\$ME (\$script_version)" "\$(date +'%F %T')"
-	tui-title "\$TITLE"
+	$beVerbose && \\
+		tui-echo "Initialize display"
+	
+	if ! \$beQuiet
+	then	tui-header "\$ME (\$script_version)" "\$(date +'%F %T')"
+		tui-title "\$TITLE"
+	fi
 #
 ## TODO : Your own stuff :)
 #
-	
+	if ! \$beQuiet
+	then	tui-echo "This is some sample test" \\
+			"with a centre" \\
+			"and right alignment"
+		
+	fi
+#
+# 	Clean up & exit
+#
+	[[ -f "\$TEMPFILE" ]] && rm -fr "\$TEMPFILE"
 EOF
