updated, tui-new-script, slightly changed its templates, and prepared for PREFIX use

diff --git a/templates/scripts/standalone b/templates/scripts/standalone
--- a/templates/scripts/standalone
+++ b/templates/scripts/standalone
@@ -33,27 +33,25 @@ cat > "$DEST" << EOF
 #	Changed:	$(date +'%Y.%m.%d')
 	script_version=0.0.1
 	TITLE="${DEST##*/}"
-#	Description:	Text TODO
-#			...  TODO
+#	Description:	
 #
 #
 #	Script Environment
 #
 	ME="\${0##*/}"				# Basename of ${DEST##*/}
 	ME="\${ME/.sh/}"				# Cut off .sh extension
-	[[ ! "." = "\$(dirname \$0)" ]] && \\
+	[ ! "." = "\$(dirname \$0)"]] && \\
 		ME_DIR="\$(dirname \$0)" || \\
 		ME_DIR="\$(pwd)"			# Dirname of ${DEST##*/}
 	CONFIG_DIR="\$HOME/.config/\$ME"		# Configuration directory
 	CONFIG="\$CONFIG_DIR/\$ME.conf"		# Configuration file
 	LOG="\$CONFIG_DIR/\$ME.log"		# Logfile
 	TEMPFILE="\$CONFIG_DIR/\$ME.tmp"		# Tempfile
-	REQUIRES="tui bash"
+	REQUIRES="bash"
 #
 #	Variable defaults (options)
 #
 	beVerbose=false
-	beQuiet=false
 	beLog=true
 #
 #	Help text
@@ -65,15 +63,46 @@ cat > "$DEST" << EOF
 \$ME (\$script_version)
 \${TITLE^}
 Usage: 		\$ME [options] arguments
-Examples:	\$ME -v
-		\$ME -q
+Examples:	\$ME 
+		\$ME -a
 		\$ME -e optVAL
 Where options are:
 	-h(elp) 		This screen
+	-C(onf			Show the config menu
 	-L(og)			Show the log file (\$LOG)
 	-q(uiet)		Mutes all output
 	-v(erbose)		Enables the scripts verbosity
+
+Files:
+--------------------------------------
+Script:		\$ME
+Script-Dir:	\$ME_DIR
+Config: 	\$CONFIG
+Config_Dir:	\$CONFIG_DIR
+Log:		\$LOG
+Tempfile:	\$TEMPFILE
 "
+#
+# This script requires TUI - Text User Interface
+# See:		https://github.com/sri-arjuna/tui
+#
+#	Check if TUI is installed...
+#
+	S=\$(which tui 2>/dev/zero )
+	if [ ! -f "\$S" ]
+	then 	[ ! 0 -eq \$UID ] && \\
+			printf "\\n#\\n#\\tPlease restart the script as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
+			exit 1
+		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
+		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
+			curl --progress-bar -L https://github.com/sri-arjuna/tui/archive/master.zip -o master.zip
+			unzip master.zip && rm -f master.zip
+			mv tui-master/* . ; rmdir tui-master
+		fi
+    		bash /tmp/tui.inst/install.sh || \\
+    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\n#\\n";exit 1)
+    	fi
+    	source \$S ; S=""
 #
 #	Configuration file template
 #
@@ -84,12 +113,11 @@ Where options are:
 #
 	beVerbose=false
 	beQuiet=false
-	beLog=false
 #
 #	Variables
 #
 	DIR_CONFIG=\"\$HOME/.config/\$ME\"
-	TEMPFILE=\"\$DIR_CONFIG/tmp.\$\$~)\"
+	TEMPFILE=\"\$DIR_CONFIG/~\$\$tmp.tmp)\"
 "
 #
 #	Functions
@@ -97,14 +125,13 @@ Where options are:
 	doLog() { # "MESSAGE STRING"
 	# Prints: Time & "Message STRING"
 	# See 'tui-log -h' for more info
-		# logVerb is set by the options
-		tui-log \$logVerb -t "\$LOG" "\$1"
+		tui-log -t "\$LOG" "\$1"
 	}
 	checkLog() { #
 	# Checks if \$LOG exists
 	# If not, create default header
 		# This is optimized for a one-time setup
-		if \$beLog && [ ! -e "\$LOG" ]
+		if \$beLog && [[ ! -e "\$LOG" ]]
 		then	[ -d "\$CONFIG_DIR" ] || mkdir -p "\$CONFIG_DIR"
 			if touch "\$LOG"
 			then	doLog "------------------------------------------" && \\
@@ -120,15 +147,11 @@ Where options are:
 #
 #	Environment checks
 #
-	# Create initial log file if logging is enabled
 	if \$beLog 
 	then	checkLog || exit \$?
 	fi
-	
-	# Create configuration file from template if not exist yet
 	[ ! -f "\$CONFIG" ] && \\
-		( tui-bol-dir "\$CONFIG_DIR" && echo "\$config_template" > "\$CONFIG" )
-
+		echo "\$config_template" > "\$CONFIG"
 ## TODO : Remove this 'source block' if you want to read the variables from CONFIG manualy
 	# Load default values before parsing options
 	if ! source "\$CONFIG" 
@@ -139,18 +162,13 @@ Where options are:
 #
 #	Install missing packages
 #
+	# This step requires the use of a config file, otherwise it will attempt to install the requirements upon each start...
 	R=\$(tui-conf-get \"\$CONFIG\" reqs_installed)
 	if [ ! true = "\$R" ]
-	then	for req in \$REQUIRES;do
-			tui-printf "Verifying: \$req..." "\$(tui-indi)"
-			if ! which \$req 2>/dev/zero 
-			then	reqs+" \$req"
-			fi
-		done
-		\$beLog && doLog "Installing: $reqs"
-		tui-install \$req && \\
+	then	tui-install \$REQUIRES && \\
 			tui-conf-get \"\$CONFIG\" reqs_installed true
 	fi
+	R=""
 #
 #	Catching Arguments
 #
@@ -168,41 +186,40 @@ Where options are:
 				-t \"\$TITLE - Configuration\" \\
 				-l \"\$LOG\" \\
 				\"\$CONFIG\"
-			exit \$?
+				
+			exit \$RET_DONE
 			;;
 		q)	beQuiet=true
 			log_msg="Forced silence"
 			;;
 		v)	beVerbose=true
 			log_msg="Enabled verbosity"
-			logVerb="-v"
 			;;
 		*)	printf "\$help_text" ; exit \$?	;;
 		esac
 		\$beLog && \\
 			doLog "Options: \$log_msg"
+		\$beVerbose && \\
+			tui-echo "\$log_msg"
 	done
 	shift \$((\$OPTIND - 1))	# All options and they (if applicable) mandatory argument are removed
 	ARGS=("\${*}")			# Remaining arguments
-	ARGS_COUNT=\${#ARGS[@]}		# Amount of remaining arguments
+	ARGS_COUNT=\${#ARGS[@]}		# Amount of remaining
 #
 #	Display & Action
 #
-	$beVerbose && \\
-		tui-echo "Initialize display"
-	
-	if ! \$beQuiet
-	then	tui-header "\$ME (\$script_version)" "\$(date +'%F %T')"
-		tui-title "\$TITLE"
-	fi
+	tui-header "\$ME (\$script_version)" "\$(date +'%F %T')"
+	tui-title "\$TITLE"
 #
 ## TODO : Your own stuff :)
 #
-	if ! \$beQuiet
-	then	tui-echo "This is some sample test" \\
-			"with a centre" \\
-			"and right alignment"
-	fi
+	tui-echo "This is some sample test" \\
+		"with a centre" \\
+		"and right alignment"
+	tui-echo "Script resides in:" 	"\$ME_DIR"
+	tui-echo "Logfile:" 		"\$LOG"
+	tui-echo "Configuration:" 	"\$CONFIG"
+	tui-echo "Temp file:"		"\$tempfile"
 #
 # 	Clean up & exit
 #
