tui-browser and tui-read update

diff --git a/templates/browser b/templates/browser
--- a/templates/browser
+++ b/templates/browser
@@ -1,23 +1,40 @@
-#!/bin/bash
+#!/usr/bin/env bash
 MORE_OPTS=""
-[[ -z $APP_USER_LABEL ]] || MORE_OPTS+=" -u '$APP_USER_LABEL'"
-[[ -z $APP_FILES ]]	|| MORE_OPTS+=" -d '$APP_FILES'"
-[[ -z $APP_FOLDERS ]]	|| MORE_OPTS+=" -f '$APP_FOLDERS'"
-[[ -z $APP_SCRIPTS ]] 	|| MORE_OPTS+=" -s '$APP_SCRIPTS'"
+[ -z $APP_USER_LABEL ]	|| MORE_OPTS+=" -u \"$APP_USER_LABEL\""
+[ -z $APP_FILES ]	|| MORE_OPTS+=" -F \"$APP_FILES\""
+[ -z $APP_FOLDERS ]	|| MORE_OPTS+=" -D \"$APP_FOLDERS\""
+[ -z $APP_SCRIPTS ] 	|| MORE_OPTS+=" -s \"$APP_SCRIPTS\""
 cat << EOF
-#!/bin/bash
-#	Description:	
-#	
-#	Author: 	$USER_NAME < $USER_EMAIL >
+#!/usr/bin/env bash
+# Project: $APP_TITLE ($APP_FILE)
+#
+# Copyright (c) $(date +%Y) $USER_NAME < $USER_EMAIL >
+# All rights reserved.
+#
+# This program is free software: you can redistribute it and/or modify it
+# under the terms of the GNU General Public License as published
+# by the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>
+# ------------------------------------------------------------------------
+#
+#	Description:	Starts the project $APP_TITLE
+#	Author:		$USER_NAME < $USER_EMAIL >
 #	Date:		$(date +'%F')
 #
-#	This script requires TUI - Text User Interface & tui-browser  by (sea)
+#	$APP_TITLE requires TUI - Text User Interface by Simon Arjuna Erat (sea)
 #	Check if TUI is installed...
 #
-	S=/etc/profile.d/tui.sh
-	if [[ ! -f \$S ]]
-	then 	[[ ! 0 -eq \$UID ]] && \\
-			printf "\\n#\\n#\\tPlease restart the script as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
+	if S=$(which tui) 2>/dev/zero # [ ! -f "\$S" ]
+	then 	[ ! 0 -eq \$UID ] && \\
+			printf "\\n#\\n#\\tPlease restart the script (\${0##*/}) as root to install TUI (Text User Interface).\\n#\\n#\\n" && \\
 			exit 1
 		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
 		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
@@ -25,42 +42,41 @@ cat << EOF
 			unzip master.zip && rm -f master.zip
 			mv tui-master/* . ; rmdir tui-master
 		fi
-    		sh /tmp/tui.inst/install.sh || \\
-    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\n#\\n";exit 1)
+    		bash /tmp/tui.inst/install.sh || \\
+    			(printf "\\n#\\n#\\tPlease report this issue of TUI installation fail.\\n#\\thttps://github.com/sri-arjuna/tui/issues\\n#\\t$(bash --version)\\n#\\n#\\n";exit 1)
     	fi
-    	source \$S ; S=""
+    	source \$S ; unset S
 #
 #	Variables
 #
-	APP_VERSION=0.1
+	ME_VERSION=0.1
 	ME="\${0##*/}"
 	ME_DIR="\${0/\${0##/*/}}"
-	ME_BASE="$APP_BASE/$APP_DATA"
-	TITLE="$APP_TITLE (\$APP_VERSION)"
+	ME_BASE="$APP_BASE/$APP_MENU"
+	TITLE="$APP_TITLE (\$ME_VERSION)"
 	MORE_OPTS="$MORE_OPTS"
 #
 #	Help text
 #
 	help_text="
-\$ME (\$script_version)
+\$ME (\$ME_VERSION)
 \${TITLE^}
 Usage: 		\$ME [options] arguments
-Examples:	\$ME 
+Examples:	\$ME help
 		\$ME 
 Where options are:
 	-h(elp) 		This screen
 "
-	case $1 in
+	case \$1 in
 	-h|--help)	printf '%s\n' "\$help_text"
 			exit 99
 			;;
 	esac
 #
-#	Display to user
+#	Action and Display
 #
-	#cd "\$ME_BASE"
 	tui-browser \\
 		-p "\$ME_BASE" \\
-		-t "\$TITLE" \\
-		\$MORE_OPTS
+		-T "\$TITLE" \\
+		\$MORE_OPTS "\${@}"
 EOF
